### ISSUE TITLE
StartWebSession not working?

### ISSUE THREAD

**Issue by wjxway** [arnoudbuzing/webunit#10]
I installed the new WebTools package, but now StartWebSession won't work......
Also when `<<WebTools`, a warning is generated which said:
`Set::wrsym: Symbol $SupportedWebDrivers is Protected.`

Am I installing the package in the wrong way?

**Comment by wjxway** [comment]
I've checked the second issue, it's probably caused by a small misspelling:
The fourth line in WebTools.m should start with `$SupportedWebDrivers::usage`

Also, after `InstallWebTools[]`, `$Context` is `"CloudObject`Private`"`, kind of wierd for me.

**Comment by wjxway** [comment]
Errrr, It's probably a bug inside Mathematica, due to the crash of `HTTPRequest` stuffs.....

**Comment by arnoudbuzing** [comment]
I think I fixed it, see if this works:

```PacletInstall @ "https://github.com/arnoudbuzing/webtools/releases/download/v0.1.0/WebTools-0.1.0.paclet"```
