### ISSUE TITLE
Import Source

### ISSUE THREAD

**Issue by ConstantineSt** [arnoudbuzing/webunit#3]
It would be great to add a function to import the webpage because some pages can be only accessed after logging in and one can't simply use standard Import function to read the page.
I think the most useful would be to get a source of current page.
Thank you in advance!

**Comment by arnoudbuzing** [comment]
@ConstantineSt So you want a snapshot of the current state of the displayed html? 

You can do this directly by doing:

`JavascriptExecute["return document.getElementsByTagName('html')[0].innerHTML;"]`

**Comment by arnoudbuzing** [comment]
Release 0.0.4 has a new function `GetPageHtml` which returns the current html for the active page:

https://github.com/arnoudbuzing/WebUnit/releases/tag/v0.0.4
