### ISSUE TITLE
WebUnit crash after opening certain webpages

### ISSUE THREAD

**Issue by wjxway** [arnoudbuzing/webunit#6]
Whenever I try to open a webpage with login panel, WebUnit crashes.
Even if I open the webpage manually, after executing arbitrary webpage manipulation program, driver crashes.( Before I execute anything,  http://localhost:9515/status returns proper result, however, after execution, which would fail,  the localhost webpage becomes unavailable )
I checked this behavior on baidu.com(I'm in China, so Google is unavailable......)/my school bbs/my school course system all result in the crash of WebUnit. What's intriguing is that baidu.com use a pop-up window to display login panel, before I click to show this pop-up window, everything is fine, but after clicking, WebUnit crashes, however, URL of the webpage doesn't change in the progress.
How could this possibly happen and how could I fix this?
Thanks again!

I checked Google, when I open google's login page, WebUnit crashes as well.

**Comment by wjxway** [comment]
Some additional information about the crash:
code: `GetPageHTML[]`
result: 
`{message->unknown error: missing or invalid 'entry.level'
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.17110 x86_64)}`
run again then it would return 
`"value" /. ImportString[$Failed, "JSON"]`
with a lot of bug report.

**Comment by wjxway** [comment]
Problem solved! The Chrome version is far ahead of driver version, resulting in a bug. Maybe you could consider updating the driver? Directly update the driver would have compatibility issues with Mathematica.

**Comment by arnoudbuzing** [comment]
I have updated the drivers. Use:

```PacletInstall @ "https://github.com/arnoudbuzing/webunit/releases/download/v0.0.5/WebUnit-0.0.5.paclet"```

to update to this new release, and let me know if this works for you.
