### ISSUE TITLE
Download Image using WebUnit

### ISSUE THREAD

**Issue by wjxway** [arnoudbuzing/webunit#7]
Is it possible for WebUnit to download images on the page?
Note that Fetching URL is not always an option, as sometimes image differs between calls even if the URLs are the same(E.G. verification code images).

**Comment by arnoudbuzing** [comment]
Have you tried something like this:

```
JavascriptExecute["
 images=document.images;
 var href = [];
 for(i=0;i<images.length;i++) {href[i]=images[i].src;}
 return href;
 "]
```

And then you can import those urls in the Wolfram Language.

**Comment by wjxway** [comment]
I've tried this, the general idea of this method is fetching URL and send another request to this URL, expecting to get an identical image. But sometimes the content inside the URL is time varying, so sending another request is not always an option...
Are there any way without involving another request?

**Comment by arnoudbuzing** [comment]
Not that I can think of.
