### ISSUE TITLE
A tricky solution to Chinese directory names

### ISSUE THREAD

**Issue by wjxway** [arnoudbuzing/webunit#8]
In the switch case in `InstallWebUnit[driver_]`, I suggest to change the code for windows to:

```
"Windows-x86-64", 
  If[
    Complement[Characters[dir],Join[CharacterRange["0", "z"], Characters@"-."]]=!={},
    SystemOpen[FileNameJoin[{ dir, "chromedriver.exe" }]],
    process = StartProcess[ $SystemShell ]; 
    WriteLine[ process, "start /b " <> FileNameJoin[{ dir, "chromedriver.exe" }] ]
  ]
```

Or else Chinese characters in `dir` would lead to initialization failure.

**Comment by arnoudbuzing** [comment]
Thanks.

Unfortunately that opens a "Command Prompt" window for me, which I don't like to see.

**Comment by arnoudbuzing** [comment]
Does `StartProcess` work for you?

For example:

```StartProcess["D:\\test\\钨\\chromedriver.exe"]```

**Comment by arnoudbuzing** [comment]
I used the above solution which seems to work for me.

Please note that I had to rename the package from `WebUnit` to `WebTools` (to avoid a compatibility issue with an upcoming release of 11.3)

This also means you have to use `InstallWebTools` instead of `InstallWebUnit`
